# Generated by Django 5.1 on 2024-08-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='satus',
            new_name='status',
        ),
    ]
